on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: rust/ares

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3

      # Makes it easier to determine why CI might differ from local linter/build
      #
      - name: Version
        run: rustc --version

      - name: Format
        run: cargo fmt --check

      # Install third-party dependencies
      #
      - name: Install dependencies
        run: |
          sudo apt-get install -y \
            libcrypto++-dev       \
            openssl               \
            cmake                 \
            libsecp256k1-dev &&
          git clone https://github.com/dfoxfranke/libaes_siv.git &&
          cd libaes_siv &&
          cmake . &&
          make &&
          sudo make install

      # See clippy linter docs: https://github.com/rust-lang/rust-clippy
      #
      # First linter is set to fail for all warnings, then ignored warnings are
      # explicitly listed
      #
      - name: Lint
        run: |
          cargo clippy \
            --all-targets \
            --no-deps \
            -- -D warnings \
            -A clippy::missing_safety_doc

      - name: Build
        run: cargo build --release --verbose

      - name: Run tests
        run: cargo test --verbose -- --test-threads=1
